dist: trusty
sudo: false

services:
  - docker

language: c

env:
  matrix:
    - TYPE=package  OS=ubuntu OS_VER=16.04 PUSH_IMAGE=1
    - TYPE=package  OS=fedora OS_VER=25    PUSH_IMAGE=1
    - TYPE=normal   OS=ubuntu OS_VER=16.04 C_COMPILER=clang CPP_COMPILER=clang++
    - TYPE=normal   OS=fedora OS_VER=25    C_COMPILER=clang CPP_COMPILER=clang++
    - TYPE=normal   OS=ubuntu OS_VER=16.04
    - TYPE=normal   OS=fedora OS_VER=25
    - TYPE=coverage OS=ubuntu OS_VER=17.04 PUSH_IMAGE=1 AUTOGENSOURCES=1
    - TYPE=sqlite   OS=ubuntu OS_VER=16.04 COVERAGE=1
    - TYPE=coverity OS=ubuntu OS_VER=16.04

before_install:
  - export HOST_WORKDIR=`pwd`
  - export GITHUB_REPO=pmem/pmemfile
  - export DOCKERHUB_REPO=pmem/pmemfile
  - export EXTRA_DOCKER_ARGS=-t
  - cd utils/docker
  - ./pull-or-rebuild-image.sh
  - if [[ -f push_image_to_repo_flag ]]; then PUSH_THE_IMAGE=1; fi
  - rm -f push_image_to_repo_flag

script:
  - ./build.sh

after_success:
  - if [[ $PUSH_THE_IMAGE -eq 1 ]]; then images/push-image.sh $OS-$OS_VER; fi
